import Head from 'next/head'
import { Inter } from '@next/font/google'
import Header from '@/app/layout/header/Header'
import NavBar from '@/app/layout/navbar/NavBar'
import Baner from '@/app/layout/baneer/Baner'
import Row from '@/app/ui/grid/Row'
const inter = Inter({ subsets: ['latin'] })

export default function Home() {
	return (
		<>
			<Head>
				<title>Home</title>
				<meta name='description' content='Generated by create next app' />
				<meta name='viewport' content='width=device-width, initial-scale=1' />
				<link rel='icon' href='/favicon.ico' />
			</Head>

			<main>
				<Header />
				<NavBar />
				<Row />
				<Baner />
			</main>
		</>
	)
}
